---
:ems:
  :ems_hawkular:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :application:
          :critical:
          - hawkular_datasource.error
          - hawkular_datasource_remove.error
          - hawkular_deployment.error
          - hawkular_deployment_remove.error
          - hawkular_jdbc.error
          - hawkular_jdbc_remove.error
          - hawkular_event.critical
          :detail:
          - hawkular_datasource.ok
          - hawkular_datasource_remove.ok
          - hawkular_deployment.ok
          - hawkular_deployment_remove.ok
          - hawkular_jdbc.ok
          - hawkular_jdbc_remove.ok
          - hawkular_event
        :power:
          :critical:
          - MwServer.Restart.UserRequest
          - MwServer.Restart.Success
          - MwServer.Restart.Failed
          - MwServer.Reload.UserRequest
          - MwServer.Reload.Success
          - MwServer.Reload.Failed
          - MwServer.Suspend.UserRequest
          - MwServer.Suspend.Success
          - MwServer.Suspend.Failed
          - MwServer.Resume.UserRequest
          - MwServer.Resume.Success
          - MwServer.Resume.Failed
          - MwServer.Shutdown.UserRequest
          - MwServer.Shutdown.Success
          - MwServer.Shutdown.Failed
          - MwServer.Start.UserRequest
          - MwServer.Start.Success
          - MwServer.Start.Failed
          - MwServer.Stop.UserRequest
          - MwServer.Stop.Success
          - MwServer.Stop.Failed
          - MwServer.Kill.UserRequest
          - MwServer.Kill.Success
          - MwServer.Kill.Failed
          - MwDomain.Stop.UserRequest
          - MwDomain.Stop.Success
          - MwDomain.Stop.Failed
    :jdr:
      :generation_timeout: 3.minutes
:ems_refresh:
  :hawkular:
    :refresh_interval: 15.minutes
:http_proxy:
  :hawkular:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_datawarehouse: info
:product:
  :datawarehouse_manager: false
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_hawkular:
        :poll: 1.minute
      :event_catcher_hawkular_datawarehouse:
        :alertable_tenants: ['_system', '_ops']
        :poll: 1.minute
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_hawkular: {}
